[headscale]
tailscale-head ansible_host=192.168.156.100 host_alias=tailscale-head.local cert_dns_sans='["tailscale-head", "tailscale-head.local"]' cert_ip_sans='["192.168.156.100"]'

[tailscale_routers]
tailscale-01 ansible_host=192.168.156.101 host_alias=site-a-router site_nic=ens224 site_cidr=10.10.10.0/24
tailscale-02 ansible_host=192.168.156.102 host_alias=site-b-router site_nic=ens224 site_cidr=10.10.20.0/24
tailscale-03 ansible_host=192.168.156.103 host_alias=site-c-router site_nic=ens37 site_cidr=10.10.30.0/24
tailscale-04 ansible_host=192.168.156.104 host_alias=site-d-router site_nic=ens37 site_cidr=10.10.40.0/24

### 테스트하지 않을 경우 아래 그룹 전체를 주석 처리하거나 삭제
[site_test_endpoints]
tailscale-01 site_test_ip=10.10.10.126
tailscale-02 site_test_ip=10.10.20.126
tailscale-03 site_test_ip=10.10.30.126
tailscale-04 site_test_ip=10.10.40.126

[tailscale:children]
headscale
tailscale_routers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_become=true
ansible_become_user=root
ansible_become_method=sudo
